RubikNube/angular-chess

angular-chess/src/app/components/chess-board.component.html, angular-chess/src/app/components/chess-board.component.ts
- grab cursor will now only be displayed if piece can be grabbed
=> grab cursor will now only be displayed if piece can be grabbed

angular-chess/src/app/services/chess-board.service.spec.ts, angular-chess/src/app/services/chess-board.service.ts, angular-chess/src/app/types/board.t.ts, angular-chess/src/app/utils/board.utils.ts
- import fen will now also supports plies
- see https://github.com/RubikNube/angular-chess/issues/7
=> Support of plies (Halbzüge) for import of FEN

angular-chess/src/app/components/move-history/move-history.component.html, angular-chess/src/app/components/move-history/move-history.component.ts, angular-chess/src/app/services/chess-board.service.spec.ts, angular-chess/src/app/services/chess-board.service.ts, angular-chess/src/app/types/board.t.ts, angular-chess/src/app/utils/board.utils.ts
- added support for move count
- see https://github.com/RubikNube/angular-chess/issues/9
=> 9_Support_of_moves_for_import_of_FEN

node_modules/.package-lock.json, package-lock.json
- removed unnecessary package-lock.json files
=> Clean Up Repository

angular-chess/src/app/components/move-history/move-history.component.html, angular-chess/src/app/components/move-history/move-history.component.ts, angular-chess/src/app/services/move-execution.service.ts, angular-chess/src/app/services/move-generation.service.ts
- added check or mate check after promotion
Steps to reproduce:
1. import "4k3/7P/8/8/8/8/1p6/4K3 w - - 0 1"
2. promote white and black pawn
Result:
=> 14_pawn_promotion_check

angular-chess/src/app/utils/board.utils.ts, angular-chess/src/app/utils/move.history.utils.ts
=> Refactoring of board utils

angular-chess/src/app/services/highlighting.service.ts, angular-chess/src/app/services/move-execution.service.ts
-- refactoring of move-execution.service.ts
=> RefactoringMoveExecutionService

angular-chess/src/app/services/move-generation.bishop.handler.ts, angular-chess/src/app/services/move-generation.king.handler.ts, angular-chess/src/app/services/move-generation.pawn.handler.ts, angular-chess/src/app/services/move-generation.queen.handler.ts, angular-chess/src/app/services/move-generation.rook.handler.ts, angular-chess/src/app/services/move-generation.service.spec.ts, angular-chess/src/app/services/move-history.service.ts, angular-chess/src/app/services/positioning.service.ts, angular-chess/src/app/utils/position.utils.ts
- refactoring of move generation
=> RefactoringOfMoveGeneration

angular-chess/src/app/utils/board.utils.spec.ts, angular-chess/src/app/utils/board.utils.ts, angular-chess/src/app/utils/piece.utils.ts
- implementation of getFen for current board
=> 21_Generate_current_FEN_for_a_given_board_position

angular-chess/src/app/app.module.ts, angular-chess/src/app/components/move-history/move-history.component.html, angular-chess/src/app/components/move-history/move-history.component.ts, angular-chess/src/app/services/chess-board.service.ts, angular-chess/src/app/services/move-execution.service.ts, angular-chess/src/app/types/pieces.t.ts, angular-chess/src/app/utils/copy.utils.ts, angular-chess/src/app/utils/position.utils.ts
- reset move with context menu in history
Example:
It resets the white/black move of the selected row.
=> Reset move in history

angular-chess/package-lock.json, angular-chess/package.json, angular-chess/src/app/app.component.html, angular-chess/src/app/app.module.ts, angular-chess/src/app/components/chess-board.component.html, angular-chess/src/app/components/chess-board.component.scss, angular-chess/src/app/components/main-menu/import-fen/import-fen.component.html, angular-chess/src/app/components/main-menu/import-fen/import-fen.component.spec.ts, angular-chess/src/app/components/main-menu/import-fen/import-fen.component.ts, angular-chess/src/app/components/main-menu/main-menu.component.html, angular-chess/src/app/components/main-menu/main-menu.component.spec.ts, angular-chess/src/app/components/main-menu/main-menu.component.ts
- implementation of main menu
See:
=> Implementation of main menu

angular-chess/src/app/services/move-generation.service.spec.ts, angular-chess/src/app/utils/board.utils.spec.ts, angular-chess/src/app/utils/board.utils.ts
- cleaned up and fixed isMate calculation
=> 26_Wrong_recognition_of_mate

angular-chess/src/app/components/chess-board.component.html, angular-chess/src/app/components/chess-board.component.scss
=> [Visual] Better current player color identification

angular-chess/src/app/components/chess-field/chess-field.component.html, angular-chess/src/app/components/chess-field/chess-field.component.scss, angular-chess/src/app/services/move-execution.service.ts, angular-chess/src/app/types/board.t.ts
- the last move is now highlighted with a blue color
=> 53_HighlightLastMove

angular-chess/src/app/components/chess-field/chess-field.component.scss
- pieces and fields can no longer be selected
=> 42-visual-you-can-select-all-piece

angular-chess/src/app/components/chess-board.component.ts, angular-chess/src/app/components/chess-field/chess-field.component.html, angular-chess/src/app/components/chess-field/chess-field.component.scss, angular-chess/src/app/services/highlighting.service.spec.ts, angular-chess/src/app/services/highlighting.service.ts, angular-chess/src/app/services/move-history.service.ts, angular-chess/src/app/utils/position.utils.ts
- last move highlighting no longer gets lost when doing an invalid move
- added tests for highlighting.service.ts with marble-testing
=> 56 last move highlighting getting lost after dropping a piece at same place

angular-chess/angular.json
=> [BUILD] no visible landing page

angular-chess/angular.json
Reverts RubikNube/angular-chess#62
=> Revert "[BUILD] no visible landing page"

angular-chess/src/app/builders/board.builder.ts, angular-chess/src/app/components/chess-board.component.ts, angular-chess/src/app/services/chess-board.service.ts, angular-chess/src/app/services/highlighting.service.spec.ts, angular-chess/src/app/services/highlighting.service.ts, angular-chess/src/app/services/move-execution.service.ts, angular-chess/src/app/services/move-generation.king.handler.ts, angular-chess/src/app/services/move-generation.pawn.handler.ts, angular-chess/src/app/services/move-generation.service.spec.ts, angular-chess/src/app/services/move-generation.service.ts, angular-chess/src/app/types/board.t.ts, angular-chess/src/app/utils/board.utils.spec.ts, angular-chess/src/app/utils/board.utils.ts, angular-chess/src/app/utils/piece.utils.ts, angular-chess/src/app/utils/position.utils.spec.ts, angular-chess/src/app/utils/position.utils.ts
- king can no longer move on attacked squares of a pawn
- castling is now only possible with tower on starting position
=> 33 king can move into a mate

angular-chess/src/app/components/chess-board.component.html, angular-chess/src/app/components/chess-board.component.ts, angular-chess/src/app/components/chess-field/chess-field.component.html, angular-chess/src/app/components/chess-field/chess-field.component.ts
- moves are now disabled when the game has finished
=> #65 Moves can be played after mate.

angular-chess/src/app/components/chess-field/chess-field.component.html, angular-chess/src/app/components/chess-field/chess-field.component.scss, angular-chess/src/app/components/chess-field/chess-field.component.ts, angular-chess/src/app/utils/position.utils.spec.ts, angular-chess/src/app/utils/position.utils.ts
* added coordinates to fields:
=> 34-feature-row-and-column-numbers-for-the-chess-board

angular-chess/angular.json, angular-chess/package-lock.json, angular-chess/package.json, angular-chess/src/app/services/chess-board.service.ts
* importing a PGN will now also load the last position and clear highlighting
=> 85 imported pgn position not displayed

angular-chess/angular.json, angular-chess/src/app/builders/board.builder.ts, angular-chess/src/app/components/chess-board.component.ts, angular-chess/src/app/components/move-history/move-history.component.html, angular-chess/src/app/components/move-history/move-history.component.scss, angular-chess/src/app/components/move-history/move-history.component.ts, angular-chess/src/app/services/chess-board.service.ts, angular-chess/src/app/types/pieces.t.ts, angular-chess/src/app/utils/move-execution.utils.ts, angular-chess/src/app/utils/pgn.utils.ts
- implementation of move navigation through history
=> 75-convenient-navigation-through-moves

angular-chess/src/app/components/move-history/move-history.component.html, angular-chess/src/app/components/move-history/move-history.component.ts
* added handling for enabling and disabling buttons
=> 90-historyarrowkeys-buttons-not-initial-grey-out-and-disabled-if-no-history-visible

angular-chess/src/app/components/move-history/move-history.component.html, angular-chess/src/app/components/move-history/move-history.component.ts
* added highlighting for moves
=> 91-historyarrowkeys-selection-not-good-visible-if-history-will-played

angular-chess/src/app/components/move-history/move-history.component.html, angular-chess/src/app/components/move-history/move-history.component.scss
* fixed positioning of history arrow keys
=> 92-historyarrowkeys-icons-do-not-fill-the-visible-space-to-the-right-end-position

angular-chess/src/app/components/move-history/move-history.component.html, angular-chess/src/app/utils/pgn.utils.ts
* added descriptions to history buttons
=> 100-add-tooltips-to-move-history-buttons

angular-chess/src/app/builders/board.builder.ts, angular-chess/src/app/utils/move-execution.utils.spec.ts, angular-chess/src/app/utils/piece.utils.ts, angular-chess/src/app/utils/test.utils.ts
* piece is no longer duplicated after promotion
=> 103 piece duplicated by promotion

angular-chess/src/app/types/pieces.t.ts, angular-chess/src/app/utils/board.utils.spec.ts, angular-chess/src/app/utils/board.utils.ts, angular-chess/src/app/utils/move-execution.utils.ts, angular-chess/src/app/utils/move-generation/move-generation.bishop.handler.ts, angular-chess/src/app/utils/move-generation/move-generation.knight.handler.ts, angular-chess/src/app/utils/move-generation/move-generation.pawn.handler.ts, angular-chess/src/app/utils/move-generation/move-generation.queen.handler.ts, angular-chess/src/app/utils/move-generation/move-generation.rook.handler.ts, angular-chess/src/app/utils/move-generation/move.generation.utils.spec.ts, angular-chess/src/app/utils/move-generation/move.generation.utils.ts, angular-chess/src/app/utils/piece.utils.spec.ts, angular-chess/src/app/utils/piece.utils.ts, angular-chess/src/app/utils/position.utils.spec.ts, angular-chess/src/app/utils/position.utils.ts, angular-chess/src/app/utils/test.utils.ts
- implementation of pinning piece contraints
=> 29 implement pinned pieces

angular-chess/src/app/components/move-history/move-history.component.ts, angular-chess/src/app/components/move-history/move-history.key-handler.ts
* implementation of move history key handler
=> 107-add-possibility-to-navigate-with-arrow-keys-in-history

angular-chess/src/app/components/move-history/move-history.component.html, angular-chess/src/app/components/move-history/move-history.component.ts, angular-chess/src/app/services/board-theming.service.ts, angular-chess/src/app/services/chess-board.service.ts, angular-chess/src/app/services/move-history.key-handler.ts, angular-chess/src/app/services/move-history.service.ts, angular-chess/src/app/services/persistence.service.ts, angular-chess/src/app/services/positioning.service.ts
=> 36 feature persits the user settings

angular-chess/src/app/utils/move-generation/move-generation.bishop.handler.spec.ts, angular-chess/src/app/utils/move-generation/move-generation.bishop.handler.ts, angular-chess/src/app/utils/move-generation/move-generation.handler.ts, angular-chess/src/app/utils/move-generation/move-generation.king.handler.spec.ts, angular-chess/src/app/utils/move-generation/move-generation.king.handler.ts, angular-chess/src/app/utils/move-generation/move-generation.knight.handler.spec.ts, angular-chess/src/app/utils/move-generation/move-generation.knight.handler.ts, angular-chess/src/app/utils/move-generation/move-generation.pawn.handler.spec.ts, angular-chess/src/app/utils/move-generation/move-generation.pawn.handler.ts, angular-chess/src/app/utils/move-generation/move-generation.queen.handler.spec.ts, angular-chess/src/app/utils/move-generation/move-generation.queen.handler.ts, angular-chess/src/app/utils/move-generation/move-generation.rook.handler.spec.ts, angular-chess/src/app/utils/move-generation/move-generation.rook.handler.ts, angular-chess/src/app/utils/move-generation/move.generation.utils.spec.ts, angular-chess/src/app/utils/move-generation/move.generation.utils.ts, angular-chess/src/app/utils/position.utils.spec.ts, angular-chess/src/app/utils/position.utils.ts
* if king is in check only moves can be now made that get the king out of check
=> 110 moves can be made that doesnt get the king out of check

angular-chess/src/app/components/chess-board.component.ts, angular-chess/src/app/services/chess-board.service.ts, angular-chess/src/app/utils/board.utils.spec.ts, angular-chess/src/app/utils/board.utils.ts, angular-chess/src/app/utils/move-execution.utils.ts, angular-chess/src/app/utils/move-generation/move-generation.bishop.handler.spec.ts, angular-chess/src/app/utils/move-generation/move-generation.bishop.handler.ts, angular-chess/src/app/utils/move-generation/move-generation.handler.ts, angular-chess/src/app/utils/move-generation/move-generation.king.handler.spec.ts, angular-chess/src/app/utils/move-generation/move-generation.king.handler.ts, angular-chess/src/app/utils/move-generation/move-generation.knight.handler.spec.ts, angular-chess/src/app/utils/move-generation/move-generation.knight.handler.ts, angular-chess/src/app/utils/move-generation/move-generation.pawn.handler.spec.ts, angular-chess/src/app/utils/move-generation/move-generation.pawn.handler.ts, angular-chess/src/app/utils/move-generation/move-generation.queen.handler.spec.ts, angular-chess/src/app/utils/move-generation/move-generation.queen.handler.ts, angular-chess/src/app/utils/move-generation/move-generation.rook.handler.spec.ts, angular-chess/src/app/utils/move-generation/move-generation.rook.handler.ts, angular-chess/src/app/utils/move-generation/move.generation.utils.spec.ts, angular-chess/src/app/utils/move-generation/move.generation.utils.ts
* king can no longer move to a square where he will be in check
* added getAttackingSquares to move generation handler
=> 112-king-can-move-to-a-square-where-he-is-still-in-check

angular-chess/package-lock.json, angular-chess/package.json, angular-chess/src/app/utils/board.utils.spec.ts, angular-chess/src/app/utils/board.utils.ts, angular-chess/src/app/utils/move-generation/move.generation.utils.spec.ts, angular-chess/src/app/utils/move-generation/move.generation.utils.ts, angular-chess/src/app/utils/piece.utils.spec.ts, angular-chess/src/app/utils/position.utils.spec.ts
* fixed issue where king can capture a piece that is protected by an enemy king
* updated dependencies and fixed tests
=> 122 king can capture protected piece

angular-chess/src/app/utils/move-generation/move-generation.pawn.handler.ts, angular-chess/src/app/utils/move-generation/move.generation.utils.spec.ts
* now en passent is no longer possible if king is in check afterwards
=> 127-en-passent-capture-ignores-check

angular-chess/package-lock.json, angular-chess/package.json, angular-chess/src/app/builders/board.builder.ts, angular-chess/src/app/components/chess-board.component.ts, angular-chess/src/app/components/move-history/move-history.component.ts, angular-chess/src/app/services/chess-board.service.ts, angular-chess/src/app/services/highlighting.service.ts, angular-chess/src/app/services/move-history.service.ts, angular-chess/src/app/services/persistence.service.ts, angular-chess/src/app/services/positioning.service.ts, angular-chess/src/app/utils/board.utils.ts, angular-chess/src/app/utils/engine.utils.spec.ts, angular-chess/src/app/utils/engine.utils.ts, angular-chess/src/app/utils/logging.utils.spec.ts, angular-chess/src/app/utils/logging.utils.ts, angular-chess/src/app/utils/move-evaluation/evaltuation.utils.ts, angular-chess/src/app/utils/move-execution.utils.ts, angular-chess/src/app/utils/move-generation/move.generation.utils.ts, angular-chess/src/app/utils/move.utils.ts, angular-chess/src/app/utils/pgn.utils.ts, angular-chess/src/app/utils/test.utils.ts, python-code/src/generate.possible.moves.py
* LoggingUtils now used a supplier for not evaluating the message directly
* added performance tests for getPossibleMoves
* added python-code/src/generate.possible.moves.py that generates possible moves for comparision
=> improved logging and added performance tests

angular-chess/src/app/utils/engine.utils.ts, angular-chess/src/app/utils/move.search.utils.spec.ts, angular-chess/src/app/utils/move.search.utils.ts
* added MoveSearchUtils to search for the best move
* the search depth is currently limited to 3 to still have a quick response
* implemented the search with the alpha beta algorithm: https://www.chessprogramming.org/Alpha-Beta
=> 126 alpha beta search

angular-chess/src/app/components/main-menu/main-menu.component.ts, angular-chess/src/app/components/move-history/move-history.component.html, angular-chess/src/app/components/move-history/move-history.component.ts, angular-chess/src/app/services/move-history.service.ts, angular-chess/src/app/utils/move.utils.spec.ts, angular-chess/src/app/utils/move.utils.ts, angular-chess/src/app/utils/pgn.utils.spec.ts, angular-chess/src/app/utils/pgn.utils.ts, angular-chess/src/app/utils/position.utils.ts
* added menu entry for exporting PGN
=> 76 export pgn

angular-chess/src/app/builders/board.builder.ts, angular-chess/src/app/services/move-history.service.ts, angular-chess/src/app/utils/copy.utils.ts, angular-chess/src/app/utils/engine.utils.spec.ts, angular-chess/src/app/utils/engine.utils.ts, angular-chess/src/app/utils/move-execution.utils.ts, angular-chess/src/app/utils/move-generation/move-generation.bishop.handler.ts, angular-chess/src/app/utils/move-generation/move-generation.king.handler.ts, angular-chess/src/app/utils/move-generation/move-generation.pawn.handler.ts, angular-chess/src/app/utils/move-generation/move-generation.queen.handler.ts, angular-chess/src/app/utils/move-generation/move-generation.rook.handler.ts, angular-chess/src/app/utils/pgn.utils.ts, angular-chess/src/app/utils/piece.utils.ts
Chrome 125.0.0.0 (Windows 10): Executed 511 of 511 SUCCESS (7.911 secs / 7.325 secs)
Chrome 125.0.0.0 (Windows 10): Executed 511 of 511 SUCCESS (4.622 secs / 4.488 secs)
=> refactor: added specific copy methods

angular-chess/src/app/builders/board.builder.ts, angular-chess/src/app/services/chess-board.service.spec.ts, angular-chess/src/app/services/chess-board.service.ts, angular-chess/src/app/types/board.t.ts, angular-chess/src/app/utils/board.utils.spec.ts, angular-chess/src/app/utils/board.utils.ts, angular-chess/src/app/utils/copy.utils.ts, angular-chess/src/app/utils/engine.utils.spec.ts, angular-chess/src/app/utils/engine.utils.ts, angular-chess/src/app/utils/move-execution.utils.ts, angular-chess/src/app/utils/move-generation/move-generation.king.handler.ts, angular-chess/src/app/utils/move-generation/move.generation.utils.spec.ts, angular-chess/src/app/utils/move-generation/move.generation.utils.ts, angular-chess/src/app/utils/square.utils.spec.ts, angular-chess/src/app/utils/test.utils.ts
* refactor: compressed castling rights type
* castle no longer possible when king is attacked
=> compressed castling rights type
